# Used for subscription emails (subscription_notifier.rb)
app_name: Recruit App
from_email: support@RecruitApp.com

# Used in account creation (account.rb)
base_domain: RecruitApp.com

# Set this to true if you want to require CC info when creating a trial account for a paid plan
require_payment_info_for_trials: true

# Credit card gateway: One of brain_tree, authorize_net_cim, payment_express, or trust_commerce
gateway: brain_tree

# Used for accessing the site admin controllers, to manage plans,
# discounts, etc.  This is prepended to base_domain, so 'admin'
# here will allow admin.example.com to serve the admin interface.
admin_subdomain: admin